//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConversationalWeed.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Literals {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Literals() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConversationalWeed.Resources.Literals", typeof(Literals).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es el turno de:.
        /// </summary>
        public static string CurrentPlayerLabel {
            get {
                return ResourceManager.GetString("CurrentPlayerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tablero de juego en la ronda: {0}.
        /// </summary>
        public static string GameBoardInfoTitle {
            get {
                return ResourceManager.GetString("GameBoardInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EL JUEGO HA TERMINADO.
        /// </summary>
        public static string GameOverLiteral {
            get {
                return ResourceManager.GetString("GameOverLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaya, parece tu mano esta rota, no puedes usar una mierda, no tienes cartas validas en este momento, lo se, es una especie de fallo en matrix pero tendras que descartar una carta. Usa !weed discard [carta_de_tu_mano].
        /// </summary>
        public static string HandBrickedMessage {
            get {
                return ResourceManager.GetString("HandBrickedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usa !weed help 2 si necesitas ayuda con los comandos de juego. Esta es tu mano:.
        /// </summary>
        public static string HandInfoMessage {
            get {
                return ResourceManager.GetString("HandInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrando información de comandos.
        /// </summary>
        public static string HelpTitle {
            get {
                return ResourceManager.GetString("HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se empieza un nuevo juego de weed con los siguientes jugadores:.
        /// </summary>
        public static string NewGame {
            get {
                return ResourceManager.GetString("NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al empezar un nuevo juego....
        /// </summary>
        public static string NewGameFailed {
            get {
                return ResourceManager.GetString("NewGameFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaya... Parece que no se ha podido jugar esta carta....
        /// </summary>
        public static string PlayCardFailed {
            get {
                return ResourceManager.GetString("PlayCardFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puntos totales: {0}.
        /// </summary>
        public static string PointsLabel {
            get {
                return ResourceManager.GetString("PointsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turnos restantes:.
        /// </summary>
        public static string RoundsLeftLabel {
            get {
                return ResourceManager.GetString("RoundsLeftLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenemos un empate entre:.
        /// </summary>
        public static string TechnicalTieLiteral {
            get {
                return ResourceManager.GetString("TechnicalTieLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Que chaval... No tienes esa skin comprada..
        /// </summary>
        public static string ValidateNoItemInPlayersInventory {
            get {
                return ResourceManager.GetString("ValidateNoItemInPlayersInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puedes entrar en parcelas custodiadas por la pasma, estas loco o que? quieres que te metan en el talego? Puto yonki de mierda....
        /// </summary>
        public static string ValidationCannotAccessBustedFields {
            get {
                return ResourceManager.GetString("ValidationCannotAccessBustedFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puedes entrar en una puta parcela custodiada por un perro de otro jugador como si nada, estas loco o que? quieres que te mate esa puta bestia? Yonki de mierda....
        /// </summary>
        public static string ValidationCannotAccessProtectedDogFields {
            get {
                return ResourceManager.GetString("ValidationCannotAccessProtectedDogFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eh tio, aqui no hay nada ilegal, la pasma no podrá hacer una mierda... .
        /// </summary>
        public static string ValidationCannotBustedNotIlegalFields {
            get {
                return ResourceManager.GetString("ValidationCannotBustedNotIlegalFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eh tio, no queremos pasarnos, la parcela de este jugador ya esta jodida por la pasma, busca otra cosa....
        /// </summary>
        public static string ValidationCannotBustedOverBusted {
            get {
                return ResourceManager.GetString("ValidationCannotBustedOverBusted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A que pretendes matar pringao? esa parcela esta puto vacia, anda fumao mirate el tablerito....
        /// </summary>
        public static string ValidationCannotKillEmptyFields {
            get {
                return ResourceManager.GetString("ValidationCannotKillEmptyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puedes plantar en una parcela con dandelion fumao....
        /// </summary>
        public static string ValidationCannotPlantInDandelion {
            get {
                return ResourceManager.GetString("ValidationCannotPlantInDandelion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solo puedes plantar hierva de igual o mejor calidad en una parcela, que chaval....
        /// </summary>
        public static string ValidationCannotPlantLessValueWeed {
            get {
                return ResourceManager.GetString("ValidationCannotPlantLessValueWeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puedes entrar a robar donde no hay nada, eres un pringao fuma chustas tio....
        /// </summary>
        public static string ValidationCannotStealEmptyFields {
            get {
                return ResourceManager.GetString("ValidationCannotStealEmptyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puedes robar tu propia cosecha fumao de mierda!.
        /// </summary>
        public static string ValidationCannotStealYourOwnFields {
            get {
                return ResourceManager.GetString("ValidationCannotStealYourOwnFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las reglas del cultivo sostenible impiden que replantes la parcela de un jugador si hay parcelas libres accesibles a su alrededor..
        /// </summary>
        public static string ValidationCannotUpgradePlantIfEmptyFieldAvailable {
            get {
                return ResourceManager.GetString("ValidationCannotUpgradePlantIfEmptyFieldAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tienes esa carta en la mano fumado....
        /// </summary>
        public static string ValidationCardNotInHand {
            get {
                return ResourceManager.GetString("ValidationCardNotInHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este campo ya tiene proteccion perruna amigo....
        /// </summary>
        public static string ValidationFieldAlreadyContainsDogProtection {
            get {
                return ResourceManager.GetString("ValidationFieldAlreadyContainsDogProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eh tio, tio, tio, tioooo... El hippie se tiene que fumar algo, aun que sea panoja... ya tu sabes primo....
        /// </summary>
        public static string ValidationHippieNeedsToSmokeSomething {
            get {
                return ResourceManager.GetString("ValidationHippieNeedsToSmokeSomething", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es tu puto turno fumao de mierda, vaya tousted....
        /// </summary>
        public static string ValidationIsNotYourTurn {
            get {
                return ResourceManager.GetString("ValidationIsNotYourTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El señor Monzon esta aqui para arreglar tus problemas, no creo que una puta parcela vacia sea el problema de nadie, fumao de mierda..
        /// </summary>
        public static string ValidationMonzonNeedsToKillSomething {
            get {
                return ResourceManager.GetString("ValidationMonzonNeedsToKillSomething", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Que chaval... No existe esa skin en la tienda..
        /// </summary>
        public static string ValidationNoItemInShop {
            get {
                return ResourceManager.GetString("ValidationNoItemInShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobre de mierda... No tienes suficientes weed coins..
        /// </summary>
        public static string ValidationNotEnoughMoney {
            get {
                return ResourceManager.GetString("ValidationNotEnoughMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El número de jugadores permitidos es de 3 a 8..
        /// </summary>
        public static string ValidationNumberOfPlayers {
            get {
                return ResourceManager.GetString("ValidationNumberOfPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El jugador {0} esta jugando en otra partida fumao....
        /// </summary>
        public static string ValidationPlayerAlreadyInGame {
            get {
                return ResourceManager.GetString("ValidationPlayerAlreadyInGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha encontrado la parcela objetivo, igual eres un poco fumao....
        /// </summary>
        public static string ValidationTargetFieldNotFound {
            get {
                return ResourceManager.GetString("ValidationTargetFieldNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha encontrado al jugador objetivo, no será que eres un fumao....
        /// </summary>
        public static string ValidationTargetPlayerNotFound {
            get {
                return ResourceManager.GetString("ValidationTargetPlayerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aún tienes alguna jugada posible en el campo, no puedes usar este comando..
        /// </summary>
        public static string ValidationYouAreNotBricked {
            get {
                return ResourceManager.GetString("ValidationYouAreNotBricked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No estas jugando ninguna partida fumao....
        /// </summary>
        public static string ValidationYouAreNotInAnyGame {
            get {
                return ResourceManager.GetString("ValidationYouAreNotInAnyGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tienes que especificar en cual de tus parcelas quieres dejar la mercancia robada..
        /// </summary>
        public static string ValidationYouMustToIncludeBeneficiaryField {
            get {
                return ResourceManager.GetString("ValidationYouMustToIncludeBeneficiaryField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solo puedes usar dandelions en parcelas vacias, que chaval....
        /// </summary>
        public static string ValidationYouOnlyCanPlantDandelionsInEmptyFields {
            get {
                return ResourceManager.GetString("ValidationYouOnlyCanPlantDandelionsInEmptyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El ganador es: {0}.
        /// </summary>
        public static string WinnerLiteral {
            get {
                return ResourceManager.GetString("WinnerLiteral", resourceCulture);
            }
        }
    }
}
